@can($form->permission())
    @if ($form->type() == 'text')
        @include('adminro::includes.dashboard.forms.text', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'email')
        @include('adminro::includes.dashboard.forms.email', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'number')
        @include('adminro::includes.dashboard.forms.number', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'tagify')
        @include('adminro::includes.dashboard.forms.tagify', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'textarea')
        @include('adminro::includes.dashboard.forms.textarea', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'date')
        @include('adminro::includes.dashboard.forms.date', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'time')
        @include('adminro::includes.dashboard.forms.time', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'file')
        @include('adminro::includes.dashboard.forms.file', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'image')
        @include('adminro::includes.dashboard.forms.image', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'video')
        @include('adminro::includes.dashboard.forms.video', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'select')
        @include('adminro::includes.dashboard.forms.select', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'multiselect')
        @include('adminro::includes.dashboard.forms.multiselect', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'switch')
        @include('adminro::includes.dashboard.forms.switch', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'map')
        @include('adminro::includes.dashboard.forms.map', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @elseif($form->type() == 'addition')
        @include('adminro::includes.dashboard.forms.addition', ['controllerSettings' => $controllerSettings, 'key' => $key, 'form' => $form])
    @endif
@endcan
